



spring:
  application:
    name: todo-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    url: "jdbc:mysql://localhost:3306/servicioUsuario"
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

#spring.datasource.url=jdbc:mysql://localhost:3306/servicioUsuario
#spring.datasource.username=root
#spring.datasource.password=

#propiedades de hibernate
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto = update


